#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmartScheduler.Resource", IsApplication=true)]

namespace SmartScheduler
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calendarsmall = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendarsmallselected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int editsmall = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int editsmallselected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_calendar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_edit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_schedule = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_settings = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int prev = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int prevday = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int second = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int secondday = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int settingssmall = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int settingssmallselected = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int thirdsmall = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int thirdsmallselected = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int WhiteButton = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int buttonOk = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int buttonOkAdd = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int calendarView1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int editTextAdd = 2131165185;
			
			// aapt resource value: 0x7f070010
			public const int editTextGroup = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int editTextMiddleName = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int editTextName = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int editTextSecondName = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int imageButton1 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int imageButtonPrev = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int imageButtonSecond = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int imageButtonSettings = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int listView1 = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int textView1 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int textView2 = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int textViewDate = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int timePicker1 = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Calendar = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Edit = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MainOld = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Schedule = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Settings = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
